version: "2"
linters:
  default: standard
  enable:
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - misspell
    - staticcheck
    - whitespace
  exclusions:
    paths:
      - _test\.go$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    